testing/coverage tests (#1)
* Coverage Tests are now working.

- **.github/workflows/build.yml** Streamlined 'Build' workflow.
- **.github/workflows/code-coverage.yml** Added a new workflow 'Code Coverage Report'
- **README.md** Added badge for Code Coverage shows the passing percentage.
- **README.md** Added code blocks for Unit Tests and Code Coverage reports.
- **package.json** Updated code coverage script and removed HTML reporters
- **package.json** Added codecov scanner and linked it to 'Code Coverage Report' GitHub Actions.

----
* Squashed commits

-  npm script 'report-coverage' uses nyc (text-reporter) and codecov.
- Reverted 'build.yml' to earlier version
- Added workflow 'Code Coverage Report' to upload results to codecov.io

* fixed typo in 'code-coverage.yml'

* Fixed typo in 'code-coverage.yml'

* Added exact verssion for Codecov and uses

* Removed comments from build.yml

* Added action versions in code-coverage.yml

- Added checkout and setup-node versions in 'code-coverage.yml'

* Formatting

* Added Code Coverage Badge

- Need to modify this with % value

* Added build job to testing/* branches.

* Added code-coverage to main and testing/*

* Removed the logic for skipping in code-coverage

* Disabled  workflow run in testing

- Code coverage and Build will always run on main but need to be  run in other branches

* Added code-cov %score

* Inline2 Added code-cov %score

* Code-cov runs on testing/coverage_tests branch

* Updated README.md and package.json

* Updated package.json, README and workflow files.

- Added '--disable=gcov' to codecov as gcov is not used.
- Added other README portion.
- 'workflow_dispatch' updated for both workflows. May not work.
- Ready for Pull Request and Review.

* Updated package.json

- Attempt to fix coverage
'ENOENT: no such file or directory, scandir '${DIR}/.nyc_output'

* Updated package.json - 2

- Attempt to fix coverage
'ENOENT: no such file or directory, scandir '${DIR}/.nyc_output'

* Updated package.json - 3

- Attempt to fix coverage
'ENOENT: no such file or directory, scandir '${DIR}/.nyc_output'

* Updated worflow files

- Attempt to fix build.yml
Missing script: "report-coverage"

* Updated worflow files - 2

- Attempt to fix build.yml
ERROR: every step must define a `uses` or `run` key